### ISSUE TITLE
Slight tweak to table format?

### ISSUE THREAD

**Issue by lintool** [osirrc/osirrc2019-library#1]
Suggestions on tweaking the format of the tables?

Run | Date | Collection | Host | Jig | Image |
:----|:----|:-----|:----|:------|:-----------|
[`anserini-20190527-robust04`](runs/anserini/0) | 2019/05/27  | Robust04 | Azure Standard_D64s_v3 | `2307f2c` yyyy/mm/dd | `dd4fbde` yyyy/mm/dd 

+ more descriptive run name
+ move collection column
+ image commit id, use 7 alphanumeric prefix (which is GitHub default) but add commit date

**Comment by ryan-clancy** [comment]
README has been updated
