### ISSUE TITLE
Finalize anserini image

### ISSUE THREAD

**Issue by lintool** [osirrc/osirrc2019-library#4]
Finalize Anserini image, version and tag - to serve as a reference template for how we are going to treat all the other images.

We should decide if we want to wait for Anserini v0.5.0:
https://github.com/castorini/anserini/issues/660

**Comment by ryan-clancy** [comment]
@lintool How that the changes in `anserini` have been merged (CAR topic reader looks almost good to go?), should we start the regressions and aim to finalize `anserini v0.5.0`, the `anserini-docker` image, and `jig` on Wednesday?

**Comment by lintool** [comment]
Yes, sounds like a reasonable timeline.

We should also update the README.md documentation on Anserini to provide a template of what we want the other docker images to look like?

**Comment by ryan-clancy** [comment]
Sure, I can update the `anserini-docker` README to have some more details...

**Comment by ryan-clancy** [comment]
Closing this as the `anserini-docker` image should be good to go...

**Comment by lintool** [comment]
@r-clancy did you test it on all collections?

**Comment by ryan-clancy** [comment]
@lintool I've tested it on the 3 smaller collections (`core17`, `core18`, `robust04`) and a subset of `cw09b`.

**Comment by lintool** [comment]
okay, let's wait until Anserini v0.5.0 release and run all everything?

**Comment by lintool** [comment]
I'm going to reopen the issue until we have v0.5.0 nailed down?

**Comment by lintool** [comment]
v0.5.0 has been released: https://search.maven.org/artifact/io.anserini/anserini/0.5.0/jar

We should be good to go... @r-clancy can you please begin the process of finalizing this image? Do the tagging, etc. Build a runbook for yourself as you'll be using the same exact procedure for all the images... i.e., we want them all tagged in a consistent manner, etc.

Run it through the jig and make sure you get the same values as those in the Anserini regression tests.

**Comment by lintool** [comment]
Done! https://zenodo.org/record/3244210#.XQPZM9NKgWo
