### ISSUE TITLE
Standardize READMEs in different image repo

### ISSUE THREAD

**Issue by lintool** [osirrc/osirrc2019-library#5]
It'd probably be a good idea to devise some sort of template so all the READMEs for the different images look similar.

**Comment by ryan-clancy** [comment]
I think the sections that [anserini-docker](https://github.com/osirrc/anserini-docker) has right now is reasonable:
- `Intro` - a quick blurb about the image, references, etc.
- `Quick Start` - instructions for running the image with `jig`
- `Expected Results` - table with `trec_eval` results for the collections

Should the `Implementation` section be saved to go in the paper?

**Comment by lintool** [comment]
Let's use https://semver.org/ for versioning.

**Comment by lintool** [comment]
Everyone seems to be happy with the template/structure of the Anserini README.
