### ISSUE TITLE
Figure out what should go in the "docker paper"

### ISSUE THREAD

**Issue by lintool** [osirrc/osirrc2019-library#6]
This is the paper in the workshop proceedings that documents each image. It might make sense to decide on some common template so they all look similar.

**Comment by r-clancy** [comment]
I think the sections that [anserini-docker](https://github.com/osirrc/anserini-docker) has right now is reasonable:
- Intro - a quick blurb about the image, references, etc.
- Quick Start - instructions for running the image with `jig`
- Expected Results - table with `trec_eval` results for the collections

Should the `Implementation` section be saved to go in the paper?

**Comment by ryan-clancy** [comment]
I think these are relatively short papers, what about having the following sections:
- `Introduction` - overview of the image, references, etc.
- `Implementation` / `Dockerization` - describe the Docker image, scripts for different hooks, etc.
- `Evaluation` - talk about the results, do they match previous regression tests, etc.
- `Conclusion` - closing thoughts, what went well, what didn't, etc.

**Comment by lintool** [comment]
This has been sorted out...
